#!/usr/bin/env python

__author__ = "Gerrit Admin <gerrit-admin@usens.com>"

import argparse
import os
import sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run ./build when present.')
    parser.add_argument('--project', metavar='PROJECT_NAME', required=True)  # project/name.git
    parser.add_argument('--refname', required=True)  # refs/heads/master
    parser.add_argument('--uploader-username', required=True)  # Werner Beroux (werner@beroux.com)
    parser.add_argument('--oldrev', metavar='SHA1', required=True)
    parser.add_argument('--newrev', metavar='SHA1', required=True)
    args = parser.parse_args()

    gerrit_site = os.environ['GERRIT_SITE']
    gerrit_tmp = os.environ['GERRIT_TMP']
    git_dir = os.environ['GIT_DIR']

    # Debug output:
    print('--project=' + args.project)
    print('--refname=' + args.refname)
    print('--uploader-username=' + args.uploader_username)
    print('--oldrev=' + args.oldrev)
    print('--newrev=' + args.newrev)
    print('GERRIT_SITE=' + gerrit_site)
    print('GERRIT_TMP=' + gerrit_tmp)
    print('GIT_DIR=' + git_dir)

sys.exit(0)
